# General Settings
style_edition = "2024"
required_version = "1.8.0"
unstable_features = true
color = "Auto"

# Width & Line Length
max_width = 100
fn_call_width = 60
attr_fn_like_width = 70
struct_lit_width = 18
struct_variant_width = 35
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50
inline_attribute_width = 0

# Indentation
hard_tabs = true
tab_spaces = 4
indent_style = "Block"
imports_indent = "Block"

# Newlines
newline_style = "Auto"

# Comments
wrap_comments = false
format_code_in_doc_comments = false
doc_comment_code_block_width = 100
comment_width = 80
normalize_comments = false
normalize_doc_attributes = false

# Strings & Macros
format_strings = false
format_macro_matchers = false
format_macro_bodies = true
skip_macro_invocations = []

# Literals
hex_literal_case = "Preserve"

# Single Line Formatting
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false

# Imports
imports_layout = "Mixed"
imports_granularity = "Preserve"
group_imports = "Preserve"
reorder_imports = true
reorder_modules = true

# Types & Punctuation
type_punctuation_density = "Wide"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false

# Operators
binop_separator = "Front"

# Expressions
remove_nested_parens = true
combine_control_expr = true
short_array_element_width_threshold = 10
overflow_delimited_expr = false

# Alignment
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0

# Match Expressions
match_arm_blocks = true
match_arm_leading_pipes = "Never"

# Functions
fn_params_layout = "Tall"

# Braces
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

# Semicolons & Commas
trailing_semicolon = true
trailing_comma = "Vertical"
match_block_trailing_comma = false

# Blank Lines
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0

# Code Style & Syntax
use_small_heuristics = "Default"
force_multiline_blocks = false
reorder_impl_items = false
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
condense_wildcard_suffixes = false

# File Handling
format_generated_files = true
generated_marker_line_search_limit = 5
ignore = []
emit_mode = "Files"
make_backup = false

# Error Handling
disable_all_formatting = false
skip_children = false
show_parse_errors = true
error_on_line_overflow = false
error_on_unformatted = false
